sudo: false
language: node_js
notifications:
  email: false
node_js:
- '6'
before_script:
- npm prune
install:
- npm install
cache:
  bundler: true
  directories:
  - node_modules
script:
- npm run test
- npm run build
branches:
  only:
  - master
before_deploy:
- npm run build
deploy:
  provider: npm
  email: al.eine@protonmail.com
  skip_cleanup: true
  local-dir: dist
  api_key:
    secure: Gw7N5xe3EKpzylIV9UJ3kXgmssdbmcOS7xWoP5hueiOOo7CVdc4XeF0bCVBr4zoRkGlQT93Lif7um12xgZXRTptgdZX9V0Q9+48fCuwUtJ2910UJI1Rh8eJe8Xo6uK0GYqqLy4iv3wQv/Sn3Vi/hYbjyRMBK2NyC4JytLlWNNKuJQlijdQNuu78Hc9JBxEEfZTlJnG3tnZdqaBNe+lrO2SDD7we+w1rsNGUIsfsCy4W9CKb5JCdFqC3lycYhxozHM2dt/lwFIrXXKpnebQOGYy2NhEEi52A2LKBGbG/CIVvDoTIkejfU18GGgPBYR8XOegrIxK2KOZ+YFkolBDoU58zXM+GWL7jHj5unmKv6Z6iOvaMDjBWPOaIBLrm5CeUKSdBIjF7CdA8Rpi1k/lvDxM+1UO0UhM7cFDVPqQedVWcK0KUU7BrJFwzuaFZLg9oijsPQlZGrL4R0WOSA+mt0re14wRAo+SGow+1V3Uq+lU7BxSI24TEElv6+4UiPKayjZLvMB4O/mrITiWIQtos66fo+Yr2gX+SRyJMpTiPdDG3kzhHmG97sxEpj9YMyeQM76xtP03TMlfcmGcxxmEp85YkBWKqYHecKcvss3cERbgSuyE9qTITIN5Y9C/J7+mp+hoq0zWHqAagRuIOjT0G2fp3FeAlT3Qoof5WQj2F3lnw=
