sudo: false
language: node_js
notifications:
  email: false
node_js:
- '10'
install:
- yarn install
cache:
  bundler: true
  directories:
  - node_modules
script:
- yarn run test
- yarn run build
branches:
  only:
  - master
before_deploy:
- yarn run build
deploy:
- provider: npm
  email: al.eine@protonmail.com
  skip_cleanup: true
  local-dir: dist
  api_key:
    secure: ph6RuYePLI5a8ogoZvp2rNZgBJxfSfnxaKEHpOTSrjD3IZcSoj1DYerRXa65CxKnnWQ0v1UxLBtK7S5GNG6JdGg9iTtFsVlV4w8zSD1JlbxsAsRoY79vca+knSL39BjrZ72XOtgNeqUo3EodjSZVaUVxUFB8NrGJMpiFOJZBUaVlfsFKOBSGbmQ+NLFQutsUmBJv/llhDjVfa1c78kW7n9qgQTl2J2bcwr614eGwYjDZ24DyMJrkqOc64UQPEFC4DKQ/osN6r8FNmpuC6oABbkuJXgoYCRq1DhrYHerXGZzwKfwZWUSX6UQQt0QzKyNY6awr6YUQs5Bh0r+b6lwdGjXKYaOxseARBcPNOFlvpbqWUwNXL0OauC6MU636O7B/fZGhYLEdxgdAlij6UGk1K7nmOIwC+pnjrpJfDB0P7YDiGcf9Eh2rnWCLWfTZ6WMcuTc8pjqbmHsDCdCK1geWN2GMxLi5G9EkoR97DWLQZn30eSeCv1AbzEWgw1uSkrG6P7xovIHMssTjtBPgZy5kAYJhc/IF+JY8xe6mHYu2du4QQDkpvE8Rf8HtQNyVVNzWn6ECZK6z24zEExAUZKeik6oYSGP2/RFOG9eBjYaRAOM0osceA6/gRgkU5ITe5yYHzVNxNSHb8n/0rrdEKq9HnQ8DA6KbsiNq0gGLlehVRUg=
