sudo: false
language: node_js
notifications:
  email: false
node_js:
- '6'
before_script:
- npm prune
install:
- npm install
cache:
  bundler: true
  directories:
  - node_modules
script:
- npm run test
- npm run build
branches:
  only:
  - master
before_deploy:
- npm run build
deploy:
  provider: npm
  email: al.eine@protonmail.com
  skip_cleanup: true
  local-dir: dist
  api_key:
    secure: NcvcYFJxWwOBZeaCCKsCK/bDZ/wacLXqUsUg0ki2HDmRa2Gz4UOUNa/LG5+4Ie+Lqyav7fV0suWq0zSAbqdY6iUcPnKRD3jK3oVv/eOSyk+qcQ7EB2BwylU4wcIV4vJxp3C/vqZEB/JRGBtZ4Ety96Ty0lMf/3JDSg6j4GKfJJxQHcgUidRFCSxBRKbGmo4rJX79za9sj/hrrXI+7u2wXAIAoKOVI3YdY8U0H3LqF0oySE4CPfwUSBJFPjObRLiNE1HC93PdhTlEUKX25IHormwoF3LPTp3TAbg727enrgmmKb7KIJT+a+hRgioQf3gujHqpCY/i0qpTwuBlEzwfoFq419T75W3t4lrXv4NnqrbuJ99rMqA+QO7xev3M3+/PcOySOWTsHIlLl4StrOfRZxIcZSwRN52Y20rZstlQjsDVs4REh5rSGH7w8td+DcSYfQnjRYMdIRXLBLol19Kd0b50iR0CHAijRy9dzzCHON+Pt1khWhT0ZIA5/SlCJC7uZChT40LhQhnjMga0uvy9e87AQwE4v0JbH3+QyaUQmX1WskQGzGJ5rjMNMCbQXVqcUkQ2WwkynR3xQl4epaW2fQGvz/y0gFTcdUnEDxYoLzShb57Wjq4MGmQ0rG5ABfgycdtuUE4sSiBR2DCEaPeayj4gvzEhz2bJZuLrMuLWpuQ=
