sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '6'

before_script:
  - npm prune

install:
  - npm install

cache:
  bundler: true
  directories:
    - node_modules

script:
  - npm run build

after_success:
  - npm run build

branches:
  only:
    - master

deploy:
  provider: npm
  email: al.eine@protonmail.com
  skip_cleanup: true
  local-dir: dist
  api_key:
    secure: k00c4Lh9aU6qJYaEzAJIlHSDF622Ln+Exi6fkI0NHCniMkkyvv34WtbCJr6BfxKzjC5fcOtOtbX31cnW/zwupsy8GcESC/DoZC5bww+u3S6DBfY2u4ZvCZs6RRaBSPKmm8feWRHp8NopZHmLrn4Uaf9QjgHPV8lGWaqmHAfD5e/RNsH+u4Qfr8kujraOQszGv7u7r2cjf7Nv8tuySBzHmcfCCH+2ycRQ/rEgJmGijPytTzl0+GVe1+Bh2MLJk+3hPMP2C2ln8VvmM+eI4yx7sYYdWvkeLy/fXbexvVE1vKeCrR9FIKD89YKgQExkP/4gJsgMA17TXYbmIw1pCKQQ74GcnBi5ej28nQC1hcbOZsMPi1CaGpDeywS70FmfY3PaSD48u7Ns9hNfKN8WuisQRMwMdrHmEqQjai3uhC76Z3TQ9k74DY5dJU1QpIm3iSBv57/Slly9JJh0rcuC38uj2REbMSdyPtmTMG3wBHzy5EhdnlUgc+qfAHzUAPQerujXt0xfZjt+64YT02FoD6luyezp6IC6ERyoBecfPuuPwY7cyOC778qa9yZDtoEveqDApzOM8x6T6JA8EoJ1FqcX4M/i54IeBBdidPAkKOxH0bAuB1kxhZjzAkoNvm9Ssq/9UHJ+3jM6f9VhYpXh6m+ynoNWM2IPErg/4TXS32x3Arw=
